credentials:
  usernames:
    ram:
      name: Ram
      password: $2b$12$7/vrvC9sx0p5G2d1oWy99.6yO3ljyh5GHukGwLDYNCZwPveUoQmKC
    alice:
      name: Alice
      password: alicepass

cookie:
  name: auth_cookie
  key: dma_dashboard
  expiry_days: 1